name: LabyrinthOfTome
main: com.yourfault.Main
version: 1.0
api-version: 1.21
commands:
  spawnnpc:
    description: Spawns a custom NPC at your location
    usage: /spawnnpc <npc_name>
    permissions:
      labyrinthoftome.admin: true
  startgame:
    description: Starts the game for debugging
    usage: /startgame [easy|medium|hard]
    permissions:
      labyrinthoftome.admin: true
  endgame:
    description: Ends the current game session
    usage: /endgame
    permissions:
      labyrinthoftome.admin: true
  get:
    description: Gives the player a special item
    usage: /get <item>
    permissions:
      labyrinthoftome.admin: true
  readyfornextwave:
    description: Triggers the next wave spawn
    usage: /readyfornextwave
    permissions:
      labyrinthoftome.admin: true
  getcoins:
    description: Grants coins for testing perks and systems
    usage: /getcoins <amount> [player]
    permissions:
        labyrinthoftome.admin: true
  createmap:
    description: Generates a circular PvE arena using procedural terrain
    usage: /createmap <x> <y> <z>
    permissions:
      labyrinthoftome.admin: true
  clearmap:
    description: Restores the world state prior to the last PvE map generation
    usage: /clearmap
    permissions:
      labyrinthoftome.admin: true
