name: LabyrinthOfTome
main: com.yourfault.Main
version: 1.0
api-version: 1.21
commands:
  startgame:
    description: Starts the game for debugging
    usage: /startgame
    permissions:
      labyrinthoftome.admin: true
  endgame:
    description: Ends the current game session
    usage: /endgame
    permissions:
      labyrinthoftome.admin: true
  get:
    description: Gives the player a special item
    usage: /get <item>
    permissions:
      labyrinthoftome.admin: true
