name: LabyrinthOfTome
main: com.yourfault.Main
version: 1.0
api-version: 1.21
commands:
  spawnnpc:
    description: Spawns a custom NPC at your location
    usage: /spawnnpc <npc_name>
    permissions:
      labyrinthoftome.admin: true
  startgame:
    description: Starts the game for debugging
    usage: /startgame [easy|medium|hard]
    permissions:
      labyrinthoftome.admin: true
  endgame:
    description: Ends the current game session
    usage: /endgame
    permissions:
      labyrinthoftome.admin: true
  get:
    description: Gives the player a special item
    usage: /get <item>
    permissions:
      labyrinthoftome.admin: true
  readyfornextwave:
    description: Triggers the next wave spawn
    usage: /readyfornextwave
    permissions:
      labyrinthoftome.admin: true
  getcoins:
    description: Grants coins for testing perks and systems
    usage: /getcoins <amount> [player]
    permissions:
      labyrinthoftome.admin: true
  createmap:
    description: Generates a circular PvE arena using procedural terrain
    usage: /createmap <x> <y> <z>
    permissions:
      labyrinthoftome.admin: true
  clearmap:
    description: Restores the world state prior to the last PvE map generation
    usage: /clearmap
    permissions:
      labyrinthoftome.admin: true
  generateboss:
    description: Spawns the boss arena structure centered on world coordinates
    usage: /generateboss <x> <y> <z>
    permissions:
      labyrinthoftome.admin: true
  clearbossroom:
    description: Clears the active boss room and restores previous blocks
    usage: /clearbossroom
    permissions:
      labyrinthoftome.admin: true
  startlot:
    description: Runs the automated LOT scenario for QA
    usage: /startLOT <x> <y> <z> [theme]
    permissions:
      labyrinthoftome.admin: true
  skipwave:
    description: Removes all remaining enemies in the current wave
    usage: /skipwave
    permissions:
      labyrinthoftome.admin: true
  damageself:
    description: Deals damage to the player for testing purposes
    usage: /damageself <amount>
    permissions:
      labyrinthoftome.admin: true
  debugtab:
    description: Debug Tab
    usage: /debugtab <header> <footer>
    permissions:
      labyrinthoftome.admin: true
  spawnmob:
    description: Spawns a specific wave enemy at your location
    usage: /spawnmob <enemy_type> [amount]
    permissions:
      labyrinthoftome.admin: true
